[{"name": "test.test_alkiot_tuplana.TuplaaAlkiotTest.test_0_paaohjelma_kunnossa", "status": "passed", "message": "", "passed": true, "points": ["5.tuplaa_alkiot"], "backtrace": []}, {"name": "test.test_alkiot_tuplana.TuplaaAlkiotTest.test_1_funktio_olemassa", "status": "failed", "message": "False is not true : Koodistasi pitäisi löytyä funktio nimeltä tuplaa_alkiot(luvut: list)", "passed": false, "points": ["5.tuplaa_alkiot"], "backtrace": ["  File \"/usr/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/notmythingy/Programming/mooc-ohjelmointi-21/osa05-06a_alkiot_tuplana/test/test_alkiot_tuplana.py\", line 34, in test_1_funktio_olemassa\n    self.assertTrue(False, 'Koodistasi pitäisi löytyä funktio nimeltä tuplaa_alkiot(luvut: list)' )\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 765, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_alkiot_tuplana.TuplaaAlkiotTest.test_2_paluuarvon_tyyppi", "status": "failed", "message": "[1]", "passed": false, "points": ["5.tuplaa_alkiot"], "backtrace": ["  File \"/usr/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/notmythingy/Programming/mooc-ohjelmointi-21/osa05-06a_alkiot_tuplana/test/test_alkiot_tuplana.py\", line 43, in test_2_paluuarvon_tyyppi\n    val = tuplaa_alkiot([1])\n", "  File \"/home/notmythingy/Programming/mooc-ohjelmointi-21/osa05-06a_alkiot_tuplana/tmc/utils.py\", line 71, in fail\n    raise AssertionError(args[0])\n"]}, {"name": "test.test_alkiot_tuplana.TuplaaAlkiotTest.test_3_listat", "status": "failed", "message": "False is not true : Varmista että funktio toimii kun syöte on \n[1, 3, 5, 7]", "passed": false, "points": ["5.tuplaa_alkiot"], "backtrace": ["  File \"/usr/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/notmythingy/Programming/mooc-ohjelmointi-21/osa05-06a_alkiot_tuplana/test/test_alkiot_tuplana.py\", line 60, in test_3_listat\n    self.assertTrue(False, f\"Varmista että funktio toimii kun syöte on \\n{test_case2}\")\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 765, in assertTrue\n    raise self.failureException(msg)\n"]}]