[{"name": "test.test_kurssin_tulokset_osa1.KurssinTuloksetOsa1Test.test_1_toimii_tiedostoilla_1", "status": "failed", "message": "False is not true : Ohjelmasi ei tulosta mitään syötteellä\nopiskelijat1.csv\ntehtavat1.csv\n\nHuomaa, että tässä tehtävässä mitään koodia EI TULE SIJOITTAA lohkon\nif __name__ == \"__main__\":\nsisälle\n", "passed": false, "points": ["6.kurssin_tulokset_osa1"], "backtrace": ["  File \"/usr/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/notmythingy/Programming/mooc-ohjelmointi-21/osa06-04_kurssin_tulokset_osa1/test/test_kurssin_tulokset_osa1.py\", line 51, in test_1_toimii_tiedostoilla_1\n    self.assertTrue(len(output_all)>0, f\"Ohjelmasi ei tulosta mitään syötteellä\\n{f(words)}\\n{mssage}\")\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 765, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_kurssin_tulokset_osa1.KurssinTuloksetOsa1Test.test_2_toimii_tiedostoilla_2", "status": "failed", "message": "False is not true : Ohjelmasi ei tulosta mitään syötteellä\nopiskelijat2.csv\ntehtavat2.csv", "passed": false, "points": ["6.kurssin_tulokset_osa1"], "backtrace": ["  File \"/usr/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/notmythingy/Programming/mooc-ohjelmointi-21/osa06-04_kurssin_tulokset_osa1/test/test_kurssin_tulokset_osa1.py\", line 78, in test_2_toimii_tiedostoilla_2\n    self.assertTrue(len(output_all)>0, f\"Ohjelmasi ei tulosta mitään syötteellä\\n{f(words)}\")\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 765, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_kurssin_tulokset_osa1.KurssinTuloksetOsa1Test.test_3_toimii_tiedostoilla_3", "status": "failed", "message": "False is not true : Ohjelmasi ei tulosta mitään syötteellä\nopiskelijat3.csv\ntehtavat3.csv", "passed": false, "points": ["6.kurssin_tulokset_osa1"], "backtrace": ["  File \"/usr/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/notmythingy/Programming/mooc-ohjelmointi-21/osa06-04_kurssin_tulokset_osa1/test/test_kurssin_tulokset_osa1.py\", line 106, in test_3_toimii_tiedostoilla_3\n    self.assertTrue(len(output_all)>0, f\"Ohjelmasi ei tulosta mitään syötteellä\\n{f(words)}\")\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 765, in assertTrue\n    raise self.failureException(msg)\n"]}, {"name": "test.test_kurssin_tulokset_osa1.KurssinTuloksetOsa1Test.test_4_toimii_tiedostoilla_4", "status": "failed", "message": "False is not true : Ohjelmasi ei tulosta mitään syötteellä\nopiskelijat4.csv\ntehtavat4.csv", "passed": false, "points": ["6.kurssin_tulokset_osa1"], "backtrace": ["  File \"/usr/lib/python3.8/unittest/case.py\", line 60, in testPartExecutor\n    yield\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 676, in run\n    self._callTestMethod(testMethod)\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 633, in _callTestMethod\n    method()\n", "  File \"/home/notmythingy/Programming/mooc-ohjelmointi-21/osa06-04_kurssin_tulokset_osa1/test/test_kurssin_tulokset_osa1.py\", line 134, in test_4_toimii_tiedostoilla_4\n    self.assertTrue(len(output_all)>0, f\"Ohjelmasi ei tulosta mitään syötteellä\\n{f(words)}\")\n", "  File \"/usr/lib/python3.8/unittest/case.py\", line 765, in assertTrue\n    raise self.failureException(msg)\n"]}]